export interface InstalacionDTO{
    id:number,
	equipo:{
        id:number,
        marca:string,
        modelo:string
    },
	fecha:Date,
	serie:string,
    direccion:string,
	empleado:{
        id:number,
        nombre:string,
        apellidos:string,
        telefono:string,
        direccion:string,
        correo:string,
        codigo:string
    },
	plan:{
        id:number,	
        velocidad:number,
        precio:number
    }
}